[package]
name = "internals"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = { version = "2.0.100" }

[features]
debug = ["syn/extra-traits"]

[dev-dependencies]
colored-diff = "0.2.3"
pretty_assertions = "1.4.1"
prettyplease = "0.2.32"
