[package]
name = "internals"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.94"
syn = "2.0.100"

[dev-dependencies]
quote = "1.0.40"
syn = { version = "2.0.100", features = ["extra-traits"] }
